### ISSUE TITLE
What's the difference to bootstrap-vue?

### ISSUE THREAD

**Issue by MarcusWichelmann** [igormatyushkin014/Vootstrap#2]
Hi,

this project got some attention from german developer-news sites that pointed me to this.

But I'm wondering if you know, that there is this really large and active project that does exactly what you're working on:
https://bootstrap-vue.js.org/

Can you please explain, what the advantages of your approach are? Why should I move to this library as soon as it's as feature complete as bootstrap-vue?

Don't get me wrong, it's always great to see new approaches and new projects. I just want to know, why you think it is reasonable to start from scratch instead of contributing to the existing project.

**Comment by igormatyushkin014** [comment]
> Why should I move to this library

You shouldn't.

> why you think it is reasonable to start from scratch instead of contributing to the existing project

Because I can.

> what the advantages of your approach are?

Tag names.
